### ISSUE TITLE
India scenario analysis: records from 10Jun2020 was not included in analysis

### ISSUE THREAD

**Issue by SM-ins** [lisphilar/covid19-sir#110]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Dear Lisphilar,

is it possible to divide the phases of India from 25th march to current date,i.e. till 17th July..in scenario analysis..,please help me if possible..

With regards,
Rakesh

**Comment by lisphilar** [comment]
Dear Rakesh/@SM-ins,
Thank you for your information!
I confirmed that records in Indea from 10Jun2020 was not included in analysis. I think `cs.JHUData` mistakenly removed these records because JHU started to collect the records at province level, not country level. I will fix this bug in the next version.
Is this you point?

**Comment by SM-ins** [comment]
Dear Lisphilar,

Thanks for your response..,Yes you are right...,I am looking for 10 June 2020 to current date..,i.e. 17 July,2020..,kindly let me know after udation.

Thankyou

**Comment by lisphilar** [comment]
Dear Rakesh,
I fixed this issue in version 2.5.4
Please kindly confirm it.
Thank you!
