### ISSUE TITLE
Date Changing issue: how to perform scenario analysis with example datasets

### ISSUE THREAD

**Issue by SM-ins** [lisphilar/covid19-sir#149]
Dear Lisphilar,

Under the section:-
Predict the number of cases: with actions from 15th day
There is a delay between the time point of starting actions and that of appearing the effect. Because  I  is the main variable, the length of delay can be estimated as sum of latent period and waiting time for confirmation. This value [day] was calculated in "SIR-F with exposed/waiting cases" section.

max(Infected) | argmax(Infected) | Infected on 17Aug2020 | Fatal on 17Aug2020
-- | -- | -- | --
232807 | 2020-03-23 | 104 | 57457
74113 | 2020-04-14 | 4197 | 37796
160879 | 2020-03-26 | 83 | 5919
221598 | 2020-03-23 | 22 | 50508

You have taken date 22 Jan as 15th day...,but I want to take 10th April as the 15th day...,so how to make changes in these scenarios...please help if possible...

With regards,
Rakesh

**Comment by lisphilar** [comment]
Dear Rakesh,
Sorry for my late reply.
No, the following codes (In[87] of the Kaggle Notebook) takes 22Jan2020 as 15th day.
Please confirm the steps commented here.
```Python
# Create province named "Lockdown" in Example country
simulator = cs.ODESimulator(country="Example", province="Lockdown")
# Add 15 days withOUT lockdown
simulator.add(
    model=cs.SIRF,
    step_n=15,
    population=eg_population,
    param_dict=param_dict,
    y0_dict={"Susceptible": 999_000, "Infected": 1000, "Recovered": 0, "Fatal": 0}
)
# Add int(latent_wating_day) days (=13 days) withOUT lockdown
simulator.add(
    model=cs.SIRF,
    step_n=int(latent_waiting_day),
    population=eg_population,
    param_dict=param_dict
)
# Add 180 days with lockdown
simulator.add(
    model=cs.SIRF,
    step_n=180,
    population=eg_population,
    param_dict=lock_param_dict
)
# Run simulation
simulator.run()
# Set 22Jan2020 as 0th day and plotting
pred_df_lock = simulator.dim(tau=eg_tau, start_date="22Jan2020").set_index("Date")
cs.line_plot(
    pred_df_lock[["Infected", "Fatal", "Recovered"]],
    "SIR-F model: Lockdown", h=eg_population, y_integer=True
)
```

This may be confusing because we are familier with `Scenario` class and `JHUData` now. However, we have `ExampleData` class (> version 2.5.0), a child class of `JHUData`, which produces example records.
Currentry, we have example/sirf_model.py and [API reference](https://lisphilar.github.io/covid19-sir/covsirphy.analysis.html#module-covsirphy.analysis.example_data), but I will create a .ipynb file to explain the usage of `ExampleData` class.

**Comment by SM-ins** [comment]
Dear @lisphilar ,

Thankyou...,it worked....

**Comment by lisphilar** [comment]
Dear Rakesh,
Usage of `ExampleData` was documented in https://lisphilar.github.io/covid19-sir/usage_theoretical.html
Please kindly create issues when you have any questions.
