### ISSUE TITLE
How to predict the number of cases accurately

### ISSUE THREAD

**Issue by lisphilar** [lisphilar/covid19-sir#3]
Topic:
How can we predict the number of cases accurately?

Note:
With version 2.0.0, we perform the following steps.
1. Split time-series data to some phases using S-R trend analysis
2. Estimate the parameter values of an ODE model using data of each phase
3. Predict parameter values of future phases using values of the last phase
4. Simulate the ODE model with predicted parameter values

Please share your ideas to update the steps/create a new approach.

**Comment by lisphilar** [comment]
Because COVID-19 crisis is ongoing, we take (should take) measures and it is difficult to find y=f(t) where t is time and y is parameter value.
However, it may be possible to find y=f(measures) by
- estimation of parameters of many phases in many countries
- gathering information about measures, including lockdown, new medicines and physical distancing
- learning the relationship of measures and parameter values

How do you think?

**Comment by lisphilar** [comment]
For learning the relationship of measures and parameters, [tslearn Python package](https://github.com/tslearn-team/tslearn) may be useful. With tslearn, we can make clusters of time series data (Rt/parameters of SIR-like models of each countries) and find patterns of time evolution.

For each pattern, we will try to create y=f(effective date of measures).

With natural language processing, it is necessary to prepare a dataset which has the effictive dates and the level of measures (lockdown etc.).
As an example, [Kaggle dataset: COVID-19 containment and mitigation measures](https://www.kaggle.com/paultimothymooney/covid19-containment-and-mitigation-measures) is daily updated.

**Comment by ilyasst** [comment]
I read this pre-print today that might be useful here: https://www.medrxiv.org/node/79983.external-links.html
A repo hosts the updated dataset (daily): https://github.com/amel-github/covid19-interventionmeasures
There is also a website to explore the dataset: http://covid19-interventions.com/

I do not know which dataset is the best, but just in case this one can be useful.

**Comment by lisphilar** [comment]
Dear @ilyasst ,
Thank you for providing the links!
I will create a Python class to analyse the data. Users will clone the [GitHub repository](https://github.com/amel-github/covid19-interventionmeasures) and get information from the dataset with the class.

For each country, we can categorize the measures with `Measure_L1`. Then, we will calculate score using `Measure_L2` and `Measure_L3` of [Master_list_CCCSL_v2_ordered.csv](https://github.com/amel-github/covid19-interventionmeasures/blob/master/Master_list_CCCSL_v2_ordered.csv)

For example, scores in "Case identification, contact tracing and related measures" category will be
L2 | L3 | Score
-- | -- | --
Activate case notification | Covid-19 as a notifiable disease | 1
Airport health check | Health certificate requested | 2
Airport health check | Health declaration | 3

In "Environmental measures' L1,
L2 | L3 | Score
-- | -- | --
Approval of new biocidal product |  None | 1
Environmental cleaning and disinfection | Airplanes | 2
Environmental cleaning and disinfection | Airports, ports and borders | 3

I could not find mentions in the preprint, but (L2, L3) with large index numbers seems more enhansed measures. Is this scoring system reliable?

**Comment by joydisette** [comment]
Hi, 
I found this dataset from oxford that gathers all measures from countries and already calculates a score. The data is updated daily (with delays for some countries depending on when they make the info public and language barriers ) They are providing an API and the dataset is also provided as time series. https://covidtracker.bsg.ox.ac.uk/ 
Here is the related github repo https://github.com/OxCGRT/covid-policy-tracker/blob/master/documentation/codebook.md
Do you think this can be useful?

**Comment by lisphilar** [comment]
Dear @joydisette ,
Thank you for your participating in this discussion!
OxCGRT you mentioned is very useful because it has reliable scoring method.
I think "data/OxCGRT_latest.csv" is more suitable as the raw data than API because we need all countries' data.

With a quick lock at the documents ([Methodology for calculating indices](https://github.com/OxCGRT/covid-policy-tracker/blob/master/documentation/index_methodology.md)) and the CSV file, I found the following useful columns:
- `GovernmentResponseIndexForDisplay`
- `StringencyIndexForDisplay`
- `ContainmentHealthIndexForDisplay`
- `EconomicSupportIndexForDisplay`

Can we predict the parameter values of SIR-F (or another) model with the four index values?

Because SIR-F parameters and the index values are phase-dependent and the start date of SIR-F does not the same as that of the index values, prediction methods will be complicated.
This needs further discussion.
Thank you.

**Comment by joydisette** [comment]
@lisphilar Since you think this can be relevant, I will look more closely and get back to you ASAP. I think we should be able to get the index and SIRF-model dates match, as for out implementation, we calculate the parameters for every new change in the curve. Cc @ilyasst  could you comment on this?

**Comment by lisphilar** [comment]
Data cleaning class was added to issue4 branch.

**Comment by lisphilar** [comment]
I merged the branch, but this issue #3 continues.

**Comment by lisphilar** [comment]
Dear @ilyasst and @joydisette ,
How can we estimate the number of change points of parameters?
CovsirPhy and my Kaggle notebook is using [S-R trend analysis](https://www.kaggle.com/lisphilar/covid-19-data-with-sir-model#S-R-trend-analysis) to find change points (not using exponential trend analysis now) and I can predict the change points with user-defined number of change points.
However, it is difficult to determine the number automatically.

S-R trend analysis:
For SIR-like models, `log10(Susceptible) = - a * Recovered + b` with constant values `(a, b)`. This is derived from the ODEs. When the model parameters change, the slope will be changed.

Thank you.

**Comment by ilyasst** [comment]
Dear @lisphilar ,

If I understand well our problem, our goal is to detect `n` trend changes for each parameter of an SIR-like model. Currently, the trend change is done using prophet, which requires the number of changepoints as an input and information about the kind of trend (linear, log, exp, ...), on the log10(susceptible). Thus, we are looking for a tool or method that can be used to detect n changepoints of a time series. 

How about this tool https://pypi.org/project/trendet/ ?

Do you think we could use it to detect the trend changes ?

**Comment by lisphilar** [comment]
Dear @ilyasst ,
Thank you for your comment and link.
Yes, the problem is how to detect the number of trend changes `n_points=0` of the parameters.
I used fbprophet in the older versions of the Kaggle notebook, but I'm using Optuna in the following step in `covsirphy.analysis.sr_change.ChangeFinder` class now.

1. Plot `log10(Susceptible)` vs. `Recovered` (`n_points=0`)
![ita_trend](https://user-images.githubusercontent.com/7270139/85012784-830f7980-b19e-11ea-80c6-7623a6200be0.png)
2. Because the regression line does not fit, `n_points+=1`
3. Optuna package suggests `n_points` change points
4. scipy.optimze.curve_fit performs curve fitting with f(x)=A exp(-Bx) for each phase (between change points)
5. Calculate weighted average of RMSLE scores
6. Repeat step 3.-5. to find better combination of change points
7. Repeat step 2.-6. to find better value of `n_points`
8. Remove 0th phase (from the first date of the dataset to the first change point) from the dataset
     - This is because the number of cases is low and it is difficult to calculate parameters of the model in 0th phase

For Italy, I assumed `n_points=4` as shown in the next figure.
![ita_change_points](https://user-images.githubusercontent.com/7270139/85012989-d97cb800-b19e-11ea-8625-2708e0887f61.png)

I tried to develop automated ChangeFinder, but step 2. (finding the best value of `n_points`) is a challenge. When `n_points` is equal to the number of days in the dataset, RMSLE score is the best. However, this is not suitable for phase-dependent anaysis certainly.

I read [the source code of trendet package](https://github.com/alvarobartt/trendet/blob/master/trendet/identification.py). Trendet is for stock time series data and seems to detect change points based on plus/minus signs of ![delta y](https://latex.codecogs.com/gif.latex?\Delta&space;y). I thik it is difficult to use this algorithm because Susceptible decreases monotonically and Recovered increases monotonically...

**Comment by ilyasst** [comment]
I have tried to look around for a solution to this problem. I believe that the solutions proposed [here by R. Killick](http://members.cbio.mines-paristech.fr/~thocking/change-tutorial/RK-CptWorkshop.html) are relevant to our problem. More specifically, the Pruned Exact Linear Time (PELT) algorithm appears to be the most interesting one as it specifically addresses the changepoint problem and aims at being fast and accurate.

The ruptures package (https://github.com/deepcharles/ruptures) offers an implementation of PELT. I tried playing around with ruptures and the Italy Suscpetible / Recovered dataset. Since the ruptures package expects a time-series (signal), I tried using it on both the Recovered and Suscpetibles data; then on the Susceptibles only and finally on the ratio of Susceptibles/Recovered.
Here is the code I have used (note that it might be possible to improve the results by better adjusting the parameters):
```python
import matplotlib.pyplot as plt
import ruptures as rpt
import pandas as pd

data_ = pd.read_csv('italy_SR_data.csv')  
signals = [data_.drop(columns = ["Date"]), 
            data_.drop(columns = ["Date", "Recovered"]),
            data_["Susceptible_actual"]/data_["Recovered"]
            ]

for data_SR in signals:
    # detection
    algo = rpt.Pelt(model="rbf", jump = 2, min_size = 6).fit(data_SR.to_numpy())
    result = algo.predict(pen=0.5)
    # display
    rpt.display(data_SR, result)
    plt.show()
```

For both the Recovered and Suscpetibles:
![photo_2020-06-19_16-30-52](https://user-images.githubusercontent.com/443955/85177521-49944800-b24a-11ea-9a6e-0d5a327fd1d6.jpg)
Note that I did not specify any breakpoints, the algorithm"found" them itself. The x axis presents time evolution (days) starting at the day the first recovery was added to the dataset (extracted from the Scenario class) which is the 2020-02-22 for Italy. The red and blue background colors show the different changepoints (or phases) detected using PELT.

When considering the Susceptibles data only:
![photo_2020-06-19_16-33-34](https://user-images.githubusercontent.com/443955/85177739-a8f25800-b24a-11ea-96f7-28759faa2fdd.jpg)

And for Suscpetibles / Recovered : 
![photo_2020-06-19_16-36-09](https://user-images.githubusercontent.com/443955/85177871-0c7c8580-b24b-11ea-9d77-48d3a30f7df3.jpg)
Since the first part of this one is hard to read, here is the same plot except that I removed the 10 first days:
![photo_2020-06-19_16-40-40](https://user-images.githubusercontent.com/443955/85178097-a80df600-b24b-11ea-8b30-74bec3a9ef9e.jpg)

Ruptures seems to be a possible solution for our problem. I could not investigate it more than this for now. There are a few things that could be improved: the jump min_size parameter 

There are a few other solutions we can look into if this one is eventually not usable (most of them seem to rely on PELT):
* https://pypi.org/project/changefinder
* https://pypi.org/project/change-finder/
* https://github.com/ruipgil/changepy

Cheers,
ilyass

**Comment by lisphilar** [comment]
Dear @ilyasst ,
Thank you ery much for information!
I agree with your idea and ruptures package is very useful for our issue.

As you mentioned, "interpolating the dataset to get a single Suscpetible value per Recovered value for example" will be necessary, because we need to use Recovered as x and Susceptible as y.

Susceptible depends on Recovered in S-R trend analysis as follows.
![\frac{\mathrm{d}S}{\mathrm{d}R}=-\frac{\beta}{N\gamma}S](https://latex.codecogs.com/gif.latex?\frac{\mathrm{d}S}{\mathrm{d}R}=-\frac{\beta}{N\gamma}S)
This means
![S(R)=Ne^{-\frac{\beta R}{N\gamma}}](https://latex.codecogs.com/gif.latex?S(R)=Ne^{-\frac{\beta&space;R}{N\gamma}})
and
![\log(S(R))=log(N)-\cfrac{\beta R}{N\gamma}](https://latex.codecogs.com/gif.latex?\log(S(R))=log(N)-\cfrac{\beta&space;R}{N\gamma})

Planed steps:
1. Convert (R, S) = (1, 1000), (2, 996), (5, 980),... to (R, S) = (1, 1000), (2, 996), (3, NA), (4, NA), (5, 980),...
2. Fill in NAs (the way to fill in NAs needs duscussion)
3. Find change points (Recovered value) with ruptunes
4. Convert Recovered value to Date

I think filling with spline curve `pandas.series.interpolate("spline", order=2)` is effective, but I need your ideas.
Thank you always.

**Comment by lisphilar** [comment]
Dear @ilyasst ,
I created "issue3" branch for this issue. 
Please help me with editing `covsirphy.analysis.sr_change.ChangeFinder` class. `run()` method will detect the change points and `show()` method will show the figure.

This is just a draft. Please use "issue3" branch for discussion and pull request.

Test codes will be saved in "tests/test_change_finder.py" file and we can perform the tests with `pipenv run pytest -v --durations=0` command.

Thank you always for your cooperation.

**Comment by lisphilar** [comment]
The following issues will be discussed in new pages.
- Keep track parameter values/reproductive number of all countries with a simple code
- Find relationship of reproductive number and measures automatically
