### ISSUE TITLE
Question about S* compartment in SIRF model

### ISSUE THREAD

**Issue by Inglezos** [lisphilar/covid19-sir#393]
## Summary of question
For SIRF model, what exactly is the S* compartment?

If I understand correctly is this the people who are actually carriers of the disease without anyone (including themselves) knowing about it, who either die and they are confirmed positive after death, while some others are moved to infected after being confirmed? Essentially you need to separate the two death situations and insert a probability factor of {a, 1-a}, right?

**Comment by lisphilar** [comment]
S* is not an actual variable. S* means this case was confirmed with COVID-19, not considering died or not.

 S* cannot exist in the real world, but I introduced this variable to create an ODE model. This is because, in this dataset, we know the number of cases who were confirmed with COVID-19, but we do not know the number of died cases who died without COVID-19.

**Comment by lisphilar** [comment]
Your understanding appears correct.

**Comment by lisphilar** [comment]
Is it necessary to documemnt this in https://lisphilar.github.io/covid19-sir/usage_theoretical.html and the kaggle Notebook?

**Comment by Inglezos** [comment]
I think yes it would be helpful for clarification.

**Comment by lisphilar** [comment]
I intend to add the following comments in SIR-F description. Please review it.

S* means this case was confirmed with COVID-19, not considering died or not.
S* cannot exist in the real world, but S* was introduced to create an SIR-F model. This is because, in JHU-style dataset, we know the number of cases who were confirmed with COVID-19, but we do not know the number of died cases who died without COVID-19.

**Comment by Inglezos** [comment]
1. For S* please add as well my clarification, "... describes the people who are actually carriers of the disease without anyone (including themselves) knowing about it, who either die and they are confirmed positive after death, while some others are moved to infected after being confirmed. Essentially it serves as an auxiliary compartment to separate the two death situations and insert a probability factor of {a, 1-a}."
2. Also add a tau interpretation/definition.

**Comment by lisphilar** [comment]
1. Thank you. I will add the following sentences to my Kaggle Notebook and https://lisphilar.github.io/covid19-sir/usage_theoretical.html#SIR-F-model

\mathrm{S}^\ast describes the cases who are actually carriers of the disease without anyone (including themselves) knowing about it, who either die and they are confirmed positive after death, while some others are moved to infected after being confirmed.

In JHU-style dataset, we know the number of cases who were confirmed with COVID-19, but we do not know the number of died cases who died without COVID-19.
Essentially \mathrm{S}^\ast serves as an auxiliary compartment in SIR-F model to separate the two death situations and insert a probability factor of {$\alpha$, $1 - \alpha$}.

2. Tau interpretation/definition is discussed in #392.

**Comment by lisphilar** [comment]
With #403, documentation was updated. This will be uploaded to the GitHub site in several hours.
I also updated my Kaggle Notebook.

**Comment by Inglezos** [comment]
Should TERM.md be also updated with S* definition as well?

**Comment by lisphilar** [comment]
Because S* is related to specific model (SIR-F model), it is expected to use https://lisphilar.github.io/covid19-sir/usage_theoretical.html and the Kaggle Notebook rather than the term list.

The update with #413 was deployed, but I found syntax error in the markdown file. This will be solved with #415 and deployed in several hours.
