### ISSUE TITLE
[New] Select plot columns and colors in Scenario.records() and .record_diff()

### ISSUE THREAD

**Issue by Inglezos** [lisphilar/covid19-sir#422]
## Summary of this new feature
It would be very useful for better visualization, if the user could select the variables (confirmed, infected, fatal, recovered) to plot, as well as the corresponding colors, when he calls `Scenario.records(country)`.

**Comment by lisphilar** [comment]
Yes, `variables=None` (default, `None` means `["Infected", "Fatal", "Recovered"]`) can be added to `covsirphy.analysis.data_handler.DataHandler.records()`.
How do you change the corresponding colors? You mean the order of variables, like `["Recovered", "Fatal", "Infected"]`?

**Comment by Inglezos** [comment]
For the colors I would think as suitable, the green for recoveries and red for fatalities. These two for sure. Now for confirmed can blue be used and orange for infected.

**Comment by lisphilar** [comment]
I'm completely used to the color set (blue for Infected, orange for Fatal, green for Recovered) :)
I'd like to carry out questionnaires if we can.

**Comment by Inglezos** [comment]
hahaha okay whatever you like, as long as recovered is green and fatal is either orange or red

**Comment by Inglezos** [comment]
@lisphilar do you have some time these days to implement this? I am not sure how to set the colors.

**Comment by lisphilar** [comment]
With #440, I updated `Scenario.records()`, `Scenario.records_diff()` and `covsirphy.line_plot()`. Please review it.

## What was changed
- Close #438 
- Users can select variables to show using `Scenario.records(variables=["Confirmed", "Recovered"])`
- Users can select color map with `Scenario.records(colormap="tab10")`
- Users can select colors with `Scenario.records(color_dict={"Infected": "blue", "Fatal": "red", "Recovered": "green"})`
- Uses can select colors in `Scenario.records_diff()` in the same way

Color map will be selected from https://matplotlib.org/examples/color/colormaps_reference.html

Figure with `Scenario.records(variables=["Confirmed", "Recovered"])`:
![Figure_1](https://user-images.githubusercontent.com/7270139/102627100-0a0fcf80-418b-11eb-87a2-cc24af03fb39.png)

Figure with `Scenario.records(colormap="tab10")`:
![Figure_1](https://user-images.githubusercontent.com/7270139/102627400-7ee30980-418b-11eb-8d08-78df0d2a29a4.png)

FIgure with `Scenario.records(color_dict={"Infected": "blue", "Fatal": "red", "Recovered": "green"})`:
![Figure_1](https://user-images.githubusercontent.com/7270139/102626778-9c63a380-418a-11eb-8f07-983749efcfc3.png)

## Additional comments regarding refactoring
We need create a new class for plotting because `covisirphy.util.plotting.line_plot()` function has too many arguments.

**Comment by lisphilar** [comment]
Should "Susceptible" be acceptable in `variables`?

**Comment by Inglezos** [comment]
I think yes it would be useful to have the option.

**Comment by Inglezos** [comment]
Have you included Susceptible in the current version?

**Comment by lisphilar** [comment]
Sorry `Scenario.records(variables=["Susceptible"])` does not work. I will fix it with #448. Please confirm it.

**Comment by lisphilar** [comment]
Follow-up completed.
