### ISSUE TITLE
Inefficetive paratial complement of Brazil recovered data

### ISSUE THREAD

**Issue by lisphilar** [lisphilar/covid19-sir#424]
## Summary
As discussed in #423, partial complement of Brazil recovered data is ineffective. The number of recovered cases increased sharply on 27Oct2020.
https://gist.github.com/lisphilar/7a737c7ceefb47316cac2010d34b5238

## (Optional) Related classes
- `covsirphy.JHUData`
- `covsirphy.JHUDataComplementHandler`

## Codes and outputs:
```Python
import covsirphy as cs
# Dataset preparation
data_loader = cs.DataLoader("input")
jhu_data = data_loader.jhu()
population_data = data_loader.population()
# Show complemented records
snl = cs.Scenario(jhu_data, population_data, "Brazil")
_ = snl.records()
```
This code creates the next figure.
![index](https://user-images.githubusercontent.com/7270139/102331161-d0de3080-3fcd-11eb-9012-018c8b0533a2.png)

## Environment
- CovsirPhy version: 2.13.0-alpha.fix.417
- Python version; 3.6
- Installation: pip
- System: Google Colaboratory

**Comment by Inglezos** [comment]
As I see the data, I think that the original source data show a jump of 400.000 recovered cases, this is not caused by any kind of our complement methods.

**Comment by lisphilar** [comment]
Is it unnecessary to create new complement methods to jump?

**Comment by Inglezos** [comment]
Since the data are valid values and they are provided as such formally, I don't think they should be handled somehow for the moment. They don't cause any trouble and they show the real cataloguing behaviour of the country. If we do handle jumps, then we smooth too much the data (what is considered as a jump?). Similar jumps for example can happen in confirmed and fatal (characteristic example is the fatal cases jump in China back in April out of sudden). We should keep these as they are, because it gets too complicated otherwise. If the jumps cause irregularities or problems we can revise this.

**Comment by lisphilar** [comment]
OK, I will mark this issue as invalid. If we or users find new problems related to these jumps, we may return to this issue.

**Comment by lisphilar** [comment]
Not "invalid", "wontfix" is correct.
