### ISSUE TITLE
[Question] Plot simulated variables for all phases (including initial)

### ISSUE THREAD

**Issue by Inglezos** [lisphilar/covid19-sir#498]
## Summary of question
What code should we run if we want to show in the simulation plot the initial phase with the corresponding simulated cases? The same question stands for all the phases where the RMSLE is too large. I just want to plot the simulated variables from the beginning. Is there already a parameter or method that does that internally? Is the answer to pass `include_init_phase=True` in `trend()` before running the estimator?

**Comment by lisphilar** [comment]
It is not visible, but shown.
If you need one variable, `Scenario.history("Infected")` may be useful.

When you want to simulate 0th phase, please use the followiing lines.
```Python
# Disable all phases
snl.disable(phases=snl.summary().summary().index.tolist())
# Enable 0th phase
snl.enable(phases=["0th"])
# Simulate
snl.simulate()
```
New argument `phases` of `Scenario.simulate()` may be useful.

**Comment by lisphilar** [comment]
`include_init_phase=True` as default and deprecated. In some old versions, this was `False` and 0th phase was removed from analysis.

**Comment by Inglezos** [comment]
What do you mean it is not visible, but shown? Due to the scaling of the plot it is too low and thus cannot be seen clearly?
We include by default the initial phase into the estimator and the simulator right? Something is happening during plotting then?
I want to plot all the phases into one single plot, just like it is now plus any initial phase simulation of cases. For example India simulation starts after June and I want to plot also the months Feb-May (initial phase) in the same plot.

**Comment by lisphilar** [comment]
What codes did you used and where are the outputs?? Did you try the codes in the previous comment??
https://gist.github.com/lisphilar/aeda986f94b91bebdbbe8d57dd097328

Out[4]:
The first date of the records (with Recovered > 0) is 13Feb2020.

Out[6]:
After parameter estiomation, 0th phase is from 13Feb2020, 1st phase is from 29Jun2020.

Out[7]:
All phases, including 0th phase, are shown. **X starts on 13Feb2020.**
Because values in 0th phase is much smaller than the max recovered value (~10,000,000), curves of 0th phase seems to overlap x-axis (i.e. not visible).

Out[9]:
Disabling all phases except for 0th phase zooms up the area with y < 400,000.
**X also starts on 13Feb2020.**

**Comment by Inglezos** [comment]
Oh yes yes, the scaling of the plots does not allow the 0th phase to be shown along with all the other phases as well, as I suspected, thank you! So all the phases, including 0th, are shown in the plot, just it may happen not to be visible sometimes.
