### ISSUE TITLE
[New] Scenario.estimate_delay() calculate the delay of any registered variables

### ISSUE THREAD

**Issue by lisphilar** [lisphilar/covid19-sir#631]
## Summary of this new feature
In version 2.16.2, `Sceanario.estimate_delay()` requires "indicator" from OxCGRT dataset and "target" from JHU dataset. With this new enhancement, both of "indicator" and "target" can be selected from any variables registered to `covsirphy.Scenario` via `.register()jhu_data, population_data, extras=[oxcgrt_data, pcr_data, vaccine_data]`).

**Comment by lisphilar** [comment]
Example: indicator="Confirmed", target="Recovered" -> recovery period in a country

**Comment by lisphilar** [comment]
Additionally, default values will be changed as discussed in #513.
Indicator: Stringency_index (as-is)
target: Infected -> Confirmed
value_range: (7, 35) -> (7, None), None means no restriction except for very long periods

**Comment by Inglezos** [comment]
>Example: indicator="Confirmed", target="Recovered" -> recovery period in a country
>
Is this example valid for ruptures analysis? Because we calculate the recovery period in another way, by matching C-F to future R, not by finding change points in the timeseries. Can this be applied indeed and give similar results?
At least with ruptures it would be more correct perhaps to pass as indicator C-F, not just C?

**Comment by lisphilar** [comment]
Sorry, not correct with the term definition of recovery period.
